version: '3.9'

services:
  mongodb:
    image: mongo:5.0.8
    restart: unless-stopped
    volumes:
    - mongo-data:/data/db
    ports:
    - 27017:27017
  redis:
    image: redis:7.0.0
    restart: unless-stopped
    volumes:
    - redis-data:/data
    ports:
    - 6379:6379
  etcd:
    image: bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    ports:
    - 2379:2379
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pgorczyca/url-shortener:local
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: app
      REDIS_URL: redis://redis:6379
      ETCD_ENDPOINTS: http://etcd:2379
      COUNTER_INCREMENT: "200"
      COUNTER_TRESHOLD: "0.8"
      PREFIX_URL: "http://localhost:8081"
    ports:
    - 8081:8080
volumes:
  mongo-data:
  redis-data: 